name: Android Dynamic Release
on:
  workflow_dispatch:
    inputs:
      TapsellAppKey:
        description: 'Tapsell App Key'
        required: true
        default: '76798342-99a7-4a5f-bf5a-60a088d5dcfb'
      AdmobAppKey:
        description: 'Admob App Key'
        required: true
        default: 'ca-app-pub-3940256099942544~3347511713'
      AppName:
        description: 'App name'
        required: true
        default: 'sample'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build Release apk
        run: |
          echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
          ./scripts/change-app.sh "${{ github.event.inputs.TapsellAppKey }}" "${{ github.event.inputs.AdmobAppKey }}" "${{ github.event.inputs.AppName }}"
          ./gradlew sample-kotlin:assembleRelease

      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: sample-kotlin/build/outputs/apk/release/*universal-release*.apk
      